packages:
  - 'packages/*'

catalog:
  '@typescript-eslint/eslint-plugin': ^5.28.0
  '@typescript-eslint/parser': ^5.28.0
  'commitizen': ^4.2.4
  'cz-conventional-changelog': 3.3.0
  'eslint': ^8.15.0
  'eslint-plugin-prettier': ^4.2.1
  'prettier': ^2.7.1
