packages:
  - packages/*

catalog:
  '@antfu/eslint-config': ^5.2.1
  '@tsconfig/node20': ^20.1.6
  '@types/lodash': ^4.17.20
  '@types/node': 24.3.0
  commitizen: ^4.2.4
  cz-conventional-changelog: 3.3.0
  eslint: ^9.34.0
  lodash: ^4.17.21
  typescript: ^5.9.2
